### ISSUE TITLE
GPU Memory Requirements

### ISSUE THREAD

**Issue by YBYBZhang** [mira-space/Mira#2]
Thanks for your excellent work! How much memory GPU is required for text-to-video generation during inference?

**Comment by Yuanshi9815** [comment]
I have tried it on different GPUs:
- 24G A5000  ❌
- 48G A6000 ✅ 

The peak memory costing is approximately  25Gb. 
I guess it could work well on 24Gb GPU if you optimize the code.

**Comment by YBYBZhang** [comment]
Thanks for your detailed reply!

**Comment by Yuanshi9815** [comment]
Update: 
Moving the `cond_stage_model` to cpu after `get_learned_conditioning()` can make it work well on 24G card.
And the memory coasting will reduce from **23G** to **7G** during the inference. 🤯

**Comment by bruinxiong** [comment]
@Yuanshi9815 could you give more detailed instruction for reducing gpu memory cost ?

**Comment by bruinxiong** [comment]
@Yuanshi9815 It's done. It costs 13G memory during the inference for 384 res.

**Comment by bruinxiong** [comment]
![image](https://github.com/mira-space/Mira/assets/3366247/1d6ded69-3ece-4e1d-83fe-875c8d717b4e)
